export const TYPES = {
  READ_STATE: "READ_STATE",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  CLEAR_CART: "CLEAR_CART",
};
